package engine

import "fmt"

func Navbar() string {

	return `
<nav style="
padding:20px 40px;
display:flex;
justify-content:space-between;
align-items:center;
">
<h2>AI Builder</h2>

<div>
<a href="#features" style="margin-right:20px;color:white">
Features
</a>

<a href="#contact" style="color:white">
Contact
</a>
</div>
</nav>
`
}

func Hero(title string, accent string) string {

	return fmt.Sprintf(`
<section style="
padding:120px 20px;
text-align:center;
">

<h1 style="
font-size:72px;
margin-bottom:20px;
">
%s
</h1>

<p style="
font-size:22px;
opacity:.8;
">
AI Generated Website
</p>

<a href="#features" style="
display:inline-block;
margin-top:40px;
padding:18px 42px;
background:%s;
border-radius:16px;
color:white;
text-decoration:none;
font-weight:bold;
">
Explore
</a>

</section>
`, title, accent)
}

func Features(card string) string {

	return fmt.Sprintf(`
<section id="features" style="
padding:60px 30px;
display:grid;
grid-template-columns:repeat(auto-fit,minmax(280px,1fr));
gap:24px;
">

<div style="
background:%s;
padding:30px;
border-radius:24px;
">
<h2>Fast</h2>
<p>Ultra fast generation.</p>
</div>

<div style="
background:%s;
padding:30px;
border-radius:24px;
">
<h2>Modern</h2>
<p>Premium responsive UI.</p>
</div>

<div style="
background:%s;
padding:30px;
border-radius:24px;
">
<h2>Scalable</h2>
<p>Concurrent multi-user support.</p>
</div>

</section>
`, card, card, card)
}

func Footer() string {

	return `
<footer id="contact" style="
padding:60px;
text-align:center;
opacity:.7;
">
Generated by AI Builder
</footer>
`
}
