package engine

import (
	"ai-builder/components" // Путь к твоим компонентам
	"fmt"
	"strings"
)

func GenerateWebsite(prompt string) string {
	// 1. Извлекаем стиль и контекст
	theme := GetTheme(prompt)
	internetData := SearchInternet(prompt)

	// 2. Начинаем сборку HTML
	html := fmt.Sprintf(`
<!DOCTYPE html>
<html lang="ru" class="scroll-smooth">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generated by AI.OS | %s</title>
    <script src="https://tailwindcss.com"></script>
    <link rel="stylesheet" href="https://unpkg.com" />
    <style>
        @import url('https://googleapis.com');
        body { font-family: 'Inter', sans-serif; overflow-x: hidden; }
        .font-premium { font-family: 'Playfair Display', serif; }
    </style>
</head>
<body class="%s %s antialiased">`, prompt, theme.Bg, theme.Text)

	// 3. Динамическая логика слоев (Intelligence Layer)
	html += components.RenderNavbar(theme)
	html += components.RenderHero(theme, prompt, internetData)

	// Если запрос про продажи — добавляем продукты
	if strings.Contains(strings.ToLower(prompt), "shop") || strings.Contains(strings.ToLower(prompt), "brand") {
		html += components.RenderProducts(theme)
	}

	html += components.RenderFeatures(theme)
	
	// Если нужно — добавляем FAQ и Pricing
	html += components.RenderPricing(theme)
	html += components.RenderFooter(theme)

	// 4. Оживляем сайт скриптами
	html += components.RenderScripts()
	html += `</body></html>`

	return html
}
